using Microsoft.Data.Sqlite;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

namespace POS_System.Security
{
    public static class AuthService
    {
        /// <summary>
        /// Login from SQLite (Users + Roles + Branch + RolePermissions)
        /// </summary>
        public static User? Login(string username, string password)
        {
            username = (username ?? "").Trim();
            password = password ?? "";

            if (string.IsNullOrWhiteSpace(username) || string.IsNullOrWhiteSpace(password))
                return null;

            using var con = new SqliteConnection(POS_System.Database.ConnStr);
            con.Open();

            using var cmd = con.CreateCommand();
            cmd.CommandText = @"
                        SELECT u.Id, u.Username, u.PasswordHash, u.IsActive,
                               r.Id AS RoleId, r.Name AS RoleName,
                               b.Id AS BranchId, b.Name AS BranchName
                        FROM Users u
                        JOIN Roles r ON r.Id = u.RoleId
                        JOIN Branches b ON b.Id = u.BranchId
                        WHERE lower(u.Username) = lower(@u)
                        LIMIT 1;
                        ";
            cmd.Parameters.AddWithValue("@u", username);

            using var rd = cmd.ExecuteReader();
            if (!rd.Read())
                return null;

            var isActive = rd.GetInt32(rd.GetOrdinal("IsActive")) == 1;
            if (!isActive)
                return null;

            var storedHash = rd.GetString(rd.GetOrdinal("PasswordHash"));
            var inputHash = Hash(password);

            // storedHash generated by Convert.ToHexString => uppercase
            if (!string.Equals(storedHash, inputHash, StringComparison.OrdinalIgnoreCase))
                return null;

            var roleId = rd.GetInt32(rd.GetOrdinal("RoleId"));
            var roleName = rd.GetString(rd.GetOrdinal("RoleName"));
            var branchName = rd.GetString(rd.GetOrdinal("BranchName"));

            var role = new Role
            {
                Name = roleName,
                Permissions = LoadRolePermissions(con, roleId)
            };

            return new User
            {
                Id = rd.GetInt32(rd.GetOrdinal("Id")),
                Username = rd.GetString(rd.GetOrdinal("Username")),
                PasswordHash = storedHash,
                IsActive = true,
                Role = role,
                BranchName = branchName
            };
        }

        private static HashSet<Permission> LoadRolePermissions(SqliteConnection con, int roleId)
        {
            var set = new HashSet<Permission>();

            using var cmd = con.CreateCommand();
            cmd.CommandText = "SELECT Permission FROM RolePermissions WHERE RoleId = @r;";
            cmd.Parameters.AddWithValue("@r", roleId);

            using var rd = cmd.ExecuteReader();
            while (rd.Read())
            {
                var p = rd.GetString(0);
                if (Enum.TryParse<Permission>(p, out var perm))
                    set.Add(perm);
            }

            return set;
        }

        /// <summary>
        /// Permission check for current session user
        /// </summary>
        public static bool HasPermission(Permission p)
        {
            var u = SessionManager.CurrentUser;
            if (u == null) return false;
            return u.Role?.Permissions?.Contains(p) == true;
        }

        /// <summary>
        /// Throws if not logged in / locked / missing permission
        /// </summary>
        public static void Demand(Permission p)
        {
            if (SessionManager.CurrentUser == null)
                throw new UnauthorizedAccessException("Not logged in.");

            if (SessionManager.IsLocked)
                throw new UnauthorizedAccessException("Session locked.");

            if (!HasPermission(p))
                throw new UnauthorizedAccessException($"Missing permission: {p}");
        }

        /// <summary>
        /// SHA256 hash (Hex). Use same for creating users/passwords.
        /// </summary>
        public static string Hash(string s)
        {
            using var sha = SHA256.Create();
            var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(s ?? ""));
            return Convert.ToHexString(bytes); // uppercase hex
        }


        public static List<LookupItem> GetUserBranches(int userId )
        {
            var list = new List<LookupItem>();

            using var con = new SqliteConnection(POS_System.Database.ConnStr);
            con.Open();

            using var cmd = con.CreateCommand();
            cmd.CommandText = @"
                    SELECT b.Id, b.Name
                    FROM UserBranches ub
                    JOIN Branches b ON b.Id = ub.BranchId
                    WHERE ub.UserId=@uid AND b.IsActive=1
                    ORDER BY b.Name;";
            cmd.Parameters.AddWithValue("@uid", userId);

            using var rd = cmd.ExecuteReader();
            while (rd.Read())
                list.Add(new LookupItem { Id = rd.GetInt32(0), Name = rd.GetString(1) });

            return list;
        }

    }
}
